version: "3.7"

services:
  success:
    build: .

    ports:
      - 3117:3000
      
    environment:
      NODE_ENV: production
      ROOT_URL: http://localhost
      PORT: 3000
      MONGO_URL: 'mongodb://success:success@mongo:27017'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: success
      MONGO_INITDB_ROOT_PASSWORD: success